# 铺垫
来自示例5-11

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
a = zeros((9,9))
a[0,4] = 1
a[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0.])

# 示例5-12

In [4]:
a[1,3] = 1
a[1,5] = 1
a[0:2]

array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.]])